/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import contentReleases from "@strapi/content-releases/strapi-admin";
import email from "@strapi/email/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "content-releases": contentReleases,
    email: email,
    "users-permissions": usersPermissions,
  },
});
